package_name: nulecule
version: 0.0.2dev
license: MIT
summary: Nulecule assistants
homepage: https://github.com/tradej/dap-nulecule
authors: [Tomas Radej <tradej@redhat.com>]
description: Assistants for manipulating Nulecule app files
dependencies: [ common_args, github ]
